import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import MainLayout from "../layouts/MainLayout";
import api from "../services/api";
import { listGiras, type Gira } from "../services/giraService";
import { readLocal } from "../lib/localStore";

const GIRAS_KEY = "casa_de_axe_giras";

export default function Dashboard() {
  const [users, setUsers] = useState(0); const [pontos, setPontos] = useState(0); const [giras, setGiras] = useState<Gira[]>(() => readLocal(GIRAS_KEY, [])); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.allSettled([api.get("/User/GetUser"), api.get("/TextoPonto"), listGiras()]).then(([usersResult, pontosResult, girasResult]) => { if (usersResult.status === "fulfilled") { const data = usersResult.value.data; setUsers(Array.isArray(data) ? data.length : Array.isArray(data?.data) ? data.data.length : 0); } if (pontosResult.status === "fulfilled") { const data = pontosResult.value.data; setPontos(Array.isArray(data) ? data.length : Array.isArray(data?.data) ? data.data.length : 0); } if (girasResult.status === "fulfilled") { setGiras(girasResult.value); localStorage.setItem(GIRAS_KEY, JSON.stringify(girasResult.value)); } }).finally(() => setLoading(false)); }, []);
  const upcoming = giras.filter((gira) => new Date(gira.data).getTime() >= Date.now()).sort((a, b) => new Date(a.data).getTime() - new Date(b.data).getTime()).slice(0, 4);
  const formatDate = (date: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(date));
  return <MainLayout><div className="space-y-6"><section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-amber-800 via-amber-900 to-stone-950 p-6 text-white shadow-lg md:p-8"><div className="relative z-10 max-w-2xl"><p className="mb-2 text-sm font-semibold uppercase tracking-wider text-amber-200">Painel da Casa</p><h1 className="text-2xl font-bold md:text-3xl">Bem-vindo(a) à Casa de Axé</h1><p className="mt-3 text-sm leading-6 text-amber-100 md:text-base">Organize suas giras, membros, guias e pontos cantados em um só lugar.</p></div><i className="bi-sun-fill absolute -bottom-10 -right-6 text-[10rem] text-white/10" /></section><div className="grid grid-cols-1 gap-4 sm:grid-cols-3">{[["Giras próximas", upcoming.length, "bi-calendar-heart", "bg-amber-100 text-amber-700"], ["Membros cadastrados", users, "bi-people", "bg-blue-100 text-blue-700"], ["Pontos no acervo", pontos, "bi-music-note-beamed", "bg-purple-100 text-purple-700"]].map(([label, value, icon, tone]) => <article key={String(label)} className="flex items-center justify-between rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-3xl font-bold text-gray-900">{loading ? "—" : value}</p></div><div className={`flex h-12 w-12 items-center justify-center rounded-full text-xl ${tone}`}><i className={String(icon)} /></div></article>)}</div><section className="rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-200 p-5"><div><h2 className="font-bold text-gray-900">Próximas giras</h2><p className="mt-1 text-sm text-gray-500">Acompanhe os próximos compromissos da Casa.</p></div><Link to="/calendario" className="text-sm font-semibold text-amber-700">Ver calendário</Link></div>{upcoming.length === 0 ? <div className="p-10 text-center text-gray-500">Nenhuma gira futura cadastrada.</div> : <div className="divide-y divide-gray-100">{upcoming.map((gira) => <div key={gira.id} className="flex items-center gap-4 p-5"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl bg-amber-50 text-amber-700"><span className="text-xl font-black">{new Date(gira.data).getDate()}</span><span className="text-[10px] font-bold uppercase">{new Date(gira.data).toLocaleDateString("pt-BR", { month: "short" }).replace(".", "")}</span></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold text-gray-900">{gira.titulo}</h3>{gira.linha && <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{gira.linha}</span>}</div><p className="mt-1 text-sm capitalize text-gray-500"><i className="bi-clock mr-1" />{formatDate(gira.data)}</p>{gira.guiaCura && <p className="mt-1 truncate text-xs text-gray-500">{gira.guiaCura}</p>}</div></div>)}</div>}</section></div></MainLayout>;
}
