import { useEffect, useMemo, useState } from "react";
import api, { isApiErrorStatus } from "../services/api";
import { listGiras, type Gira } from "../services/giraService";

type Ponto = { id: number; tituloDoponto?: string; tituloDoPonto?: string; letraDoPonto?: string; categoriaDoPontos?: string; linkDoYouTube?: string };
type InstagramMedia = { id: string; caption?: string; media_type?: string; media_url?: string; thumbnail_url?: string; permalink?: string; timestamp?: string };

const instagramProfile = "https://www.instagram.com/tendasaojeronimo_/";
const pontoEndpoint = import.meta.env.VITE_PONTOS_ENDPOINT || "/TextoPonto";
const instagramEndpoint = (import.meta.env.VITE_INSTAGRAM_FEED_URL || "/instagram").replace(/^\/api(?=\/)/, "");

function listFromResponse<T>(data: unknown): T[] {
  if (Array.isArray(data)) return data as T[];
  if (data && typeof data === "object" && Array.isArray((data as { data?: unknown[] }).data)) return (data as { data: T[] }).data;
  return [];
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "2-digit", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

export default function SitePublico() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [giras, setGiras] = useState<Gira[]>([]);
  const [pontos, setPontos] = useState<Ponto[]>([]);
  const [instagram, setInstagram] = useState<InstagramMedia[]>([]);
  const [loading, setLoading] = useState(true);
  const [instagramLoading, setInstagramLoading] = useState(true);
  const [instagramUnavailable, setInstagramUnavailable] = useState(false);

  useEffect(() => {
    Promise.allSettled([
      listGiras(),
      api.get(pontoEndpoint, { requiresAuth: false }),
    ]).then(([girasResult, pontosResult]) => {
      if (girasResult.status === "fulfilled") setGiras(girasResult.value);
      if (pontosResult.status === "fulfilled") setPontos(listFromResponse<Ponto>(pontosResult.value.data));
    }).finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    api.get(instagramEndpoint, { requiresAuth: false })
      .then(({ data }) => setInstagram(listFromResponse<InstagramMedia>(data).slice(0, 9)))
      .catch((error) => {
        setInstagram([]);
        setInstagramUnavailable(isApiErrorStatus(error, 503));
      })
      .finally(() => setInstagramLoading(false));
  }, []);

  const upcoming = useMemo(() => giras.filter((gira) => new Date(gira.data).getTime() >= Date.now()).sort((a, b) => new Date(a.data).getTime() - new Date(b.data).getTime()).slice(0, 3), [giras]);
  const featuredPoints = pontos.slice(0, 4);

  return <div className="min-h-screen bg-[#fbf8f3] text-stone-900">
    <header className="sticky top-0 z-40 border-b border-stone-200/80 bg-[#fbf8f3]/95 backdrop-blur"><div className="relative mx-auto flex h-20 max-w-7xl items-center justify-between gap-3 px-5 lg:px-8"><a href="#inicio" className="flex shrink-0 items-center gap-3"><img src="/images/logo.svg" alt="Casa de Axé Ilê Tenda São Gerônimo" className="h-12 w-auto" /><span className="hidden text-sm font-bold uppercase tracking-[.16em] text-amber-900 sm:block">Ilê Tenda<br />São Gerônimo</span></a><nav className={`${mobileMenuOpen ? "absolute left-0 right-0 top-20 flex flex-col border-b border-stone-200 bg-[#fbf8f3] p-5 shadow-lg" : "hidden"} gap-5 text-sm font-medium text-stone-600 md:static md:flex md:flex-row md:border-0 md:bg-transparent md:p-0 md:shadow-none`}><a href="#giras" onClick={() => setMobileMenuOpen(false)} className="hover:text-amber-800">Giras</a><a href="#pontos" onClick={() => setMobileMenuOpen(false)} className="hover:text-amber-800">Pontos</a><a href="#instagram" onClick={() => setMobileMenuOpen(false)} className="hover:text-amber-800">Instagram</a><a href="#casa" onClick={() => setMobileMenuOpen(false)} className="hover:text-amber-800">A Casa</a></nav><div className="flex items-center gap-2"><a href="/login" className="rounded-full border border-amber-800 px-3 py-2 text-sm font-semibold text-amber-900 transition hover:bg-amber-50 sm:px-4">Entrar</a><a href="/cadastro" className="hidden rounded-full bg-amber-100 px-3 py-2 text-sm font-semibold text-amber-900 transition hover:bg-amber-200 sm:inline-flex sm:px-4">Criar conta</a><a href={instagramProfile} target="_blank" rel="noreferrer" aria-label="Siga a Casa no Instagram" className="rounded-full bg-amber-800 px-3 py-2 text-sm font-semibold text-white transition hover:bg-amber-900 sm:px-4"><i className="bi-instagram sm:mr-2" /><span className="hidden sm:inline">Siga a Casa</span></a><button type="button" aria-label="Abrir menu" aria-expanded={mobileMenuOpen} onClick={() => setMobileMenuOpen((open) => !open)} className="rounded-full border border-stone-300 p-2 text-stone-700 md:hidden"><i className={mobileMenuOpen ? "bi-x-lg" : "bi-list"} /></button></div></div></header>

    <main>
      <section id="inicio" className="relative isolate overflow-hidden"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_15%,rgba(180,83,9,.18),transparent_35%),radial-gradient(circle_at_15%_80%,rgba(22,101,52,.14),transparent_30%)]" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div><p className="mb-5 text-sm font-bold uppercase tracking-[.24em] text-amber-800">Acolhimento, fé e tradição</p><h1 className="max-w-3xl text-5xl font-black leading-[1.05] tracking-tight text-stone-950 md:text-7xl">Um espaço para cuidar, aprender e caminhar junto.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-stone-600">Conheça a programação da Casa, acompanhe nossas giras e encontre os pontos que fazem parte da nossa caminhada.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#giras" className="rounded-full bg-amber-800 px-6 py-3 font-semibold text-white transition hover:bg-amber-900">Ver próximas giras <i className="bi-arrow-down ml-2" /></a><a href={instagramProfile} target="_blank" rel="noreferrer" className="rounded-full border border-stone-300 bg-white/70 px-6 py-3 font-semibold text-stone-700 transition hover:border-amber-500 hover:text-amber-800"><i className="bi-instagram mr-2" />Ver no Instagram</a></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-4 rounded-[2.5rem] bg-amber-900/10 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/70 bg-gradient-to-br from-amber-900 via-stone-900 to-emerald-950 p-8 text-white shadow-2xl md:p-12"><div className="flex h-72 flex-col justify-between rounded-2xl border border-white/15 bg-white/5 p-7 backdrop-blur-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-amber-100">Nossa Casa</span><i className="bi-sun text-3xl text-amber-200" /></div><div><p className="text-4xl font-black leading-tight">Ilê Tenda<br />São Gerônimo</p><p className="mt-3 text-sm text-amber-100">Axé para todos os caminhos.</p></div></div></div></div></div></section>

      <section id="giras" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-20 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-800">Programação</p><h2 className="mt-2 text-4xl font-black tracking-tight">Próximas giras</h2><p className="mt-3 max-w-xl text-stone-600">Confira os próximos encontros e programe sua presença com antecedência.</p></div><a href="/login" className="font-semibold text-amber-800 hover:text-amber-950">Área da Casa <i className="bi-arrow-up-right ml-1" /></a></div>{loading ? <div className="rounded-2xl border border-stone-200 bg-white p-10 text-center text-stone-500"><i className="bi-arrow-repeat mr-2 animate-spin" />Carregando programação...</div> : upcoming.length === 0 ? <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-10 text-center text-stone-500">Novas giras serão divulgadas em breve.</div> : <div className="grid gap-5 lg:grid-cols-3">{upcoming.map((gira) => <article key={gira.id} className="group rounded-2xl border border-stone-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="mb-7 flex items-start justify-between"><div className="flex h-16 w-16 flex-col items-center justify-center rounded-2xl bg-amber-50 text-amber-800"><span className="text-2xl font-black">{new Date(gira.data).getDate()}</span><span className="text-[10px] font-bold uppercase">{new Date(gira.data).toLocaleDateString("pt-BR", { month: "short" }).replace(".", "")}</span></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">Aberta ao público</span></div><h3 className="text-xl font-bold text-stone-900">{gira.titulo}</h3><p className="mt-3 text-sm capitalize leading-6 text-stone-500"><i className="bi-calendar3 mr-2 text-amber-700" />{formatDate(gira.data)}</p>{gira.guiaCura && <p className="mt-2 text-sm text-stone-600"><i className="bi-stars mr-2 text-amber-700" />{gira.guiaCura}</p>}<p className="mt-6 border-t border-stone-100 pt-4 text-sm font-semibold text-amber-800">Saiba mais na Área da Casa <i className="bi-arrow-right ml-1 transition group-hover:ml-2" /></p></article>)}</div>}</section>

      <section id="pontos" className="scroll-mt-24 bg-stone-900 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-300">Memória e canto</p><h2 className="mt-3 text-4xl font-black tracking-tight">Pontos cantados</h2><p className="mt-5 max-w-md leading-7 text-stone-300">Um pequeno recorte do nosso acervo. Na área reservada, os filhos da Casa podem consultar letras, categorias e referências.</p><a href="/login" className="mt-8 inline-flex rounded-full bg-amber-600 px-5 py-3 font-semibold text-white hover:bg-amber-500">Acessar acervo <i className="bi-arrow-right ml-2" /></a></div><div>{featuredPoints.length === 0 ? <div className="rounded-2xl border border-white/10 bg-white/5 p-10 text-stone-300">O acervo público será atualizado em breve.</div> : <div className="grid gap-3 sm:grid-cols-2">{featuredPoints.map((ponto) => <article key={ponto.id} className="rounded-2xl border border-white/10 bg-white/5 p-5 transition hover:bg-white/10"><i className="bi-music-note-beamed text-2xl text-amber-300" /><h3 className="mt-5 font-bold">{ponto.tituloDoponto || ponto.tituloDoPonto || "Ponto cantado"}</h3><p className="mt-2 text-xs uppercase tracking-wider text-stone-400">{ponto.categoriaDoPontos || "Acervo da Casa"}</p>{ponto.linkDoYouTube && <a href={ponto.linkDoYouTube} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-amber-300 hover:text-amber-200">Ouvir referência <i className="bi-box-arrow-up-right ml-1" /></a>}</article>)}</div>}</div></div></section>

      <section id="instagram" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-20 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-800">Siga de perto</p><h2 className="mt-2 text-4xl font-black tracking-tight">Do Instagram para cá</h2><p className="mt-3 max-w-xl text-stone-600">Registros, avisos e momentos da nossa comunidade.</p></div><a href={instagramProfile} target="_blank" rel="noreferrer" className="font-semibold text-amber-800 hover:text-amber-950">@tendasaojeronimo_ <i className="bi-arrow-up-right ml-1" /></a></div>{instagramLoading ? <div className="grid grid-cols-2 gap-3 md:grid-cols-3"><div className="aspect-square animate-pulse rounded-2xl bg-stone-200" /><div className="aspect-square animate-pulse rounded-2xl bg-stone-200" /><div className="aspect-square animate-pulse rounded-2xl bg-stone-200" /></div> : instagram.length === 0 ? <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-10 text-center"><i className="bi-instagram mb-3 block text-3xl text-amber-800" /><p className="text-stone-600">{instagramUnavailable ? "O feed está temporariamente indisponível. Tente novamente mais tarde." : "Acompanhe as novidades diretamente no Instagram."}</p><a href={instagramProfile} target="_blank" rel="noreferrer" className="mt-4 inline-block rounded-full bg-amber-800 px-5 py-2.5 font-semibold text-white hover:bg-amber-900">Abrir Instagram</a></div> : <div className="grid grid-cols-2 gap-3 md:grid-cols-3">{instagram.map((post) => <a key={post.id} href={post.permalink || instagramProfile} target="_blank" rel="noreferrer" className="group relative aspect-square overflow-hidden rounded-2xl bg-stone-200"><img src={post.media_url || post.thumbnail_url} alt={post.caption?.slice(0, 120) || "Publicação da Casa de Axé"} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 flex items-end bg-gradient-to-t from-black/70 via-transparent to-transparent p-4 opacity-0 transition group-hover:opacity-100"><p className="line-clamp-3 text-xs text-white">{post.caption}</p></div>{post.media_type === "VIDEO" && <i className="bi-play-circle-fill absolute right-3 top-3 text-xl text-white drop-shadow" />}</a>)}</div>}</section>

      <section id="casa" className="border-t border-stone-200 bg-amber-50"><div className="mx-auto max-w-4xl px-5 py-20 text-center lg:px-8"><i className="bi-heart-fill text-3xl text-amber-800" /><h2 className="mt-5 text-3xl font-black">Um lugar de respeito, cuidado e axé.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-stone-600">Nossa casa acolhe pessoas em busca de conhecimento, orientação e conexão com a espiritualidade. Para saber mais sobre uma gira, acompanhe nossa programação e nossos canais oficiais.</p><a href={instagramProfile} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full border border-amber-800 px-6 py-3 font-semibold text-amber-900 hover:bg-amber-800 hover:text-white">Falar com a Casa pelo Instagram</a></div></section>
    </main>

    <footer className="bg-stone-950 px-5 py-10 text-stone-400"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm sm:flex-row sm:items-center lg:px-8"><p>© {new Date().getFullYear()} Ilê Tenda São Gerônimo</p><div className="flex gap-5"><a href={instagramProfile} target="_blank" rel="noreferrer" className="hover:text-white"><i className="bi-instagram mr-2" />Instagram</a><a href="/login" className="hover:text-white">Área da Casa</a></div></div></footer>
  </div>;
}
